config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :alunos
  root 'alunos#new'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  validates :nome, presence: { message: "É obrigatório informar o nome!" }
  validates :email, presence: { message: "É obrigatório informar o email!" }, format: { with: URI::MailTo::EMAIL_REGEXP,
      message: "Formato de e-mail inválido!" } 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  def new
      @aluno = Aluno.new
  end

  def create
    @aluno = Aluno.new(aluno_params) 
    if @aluno.save
      redirect_to @aluno
    else
      render 'new'
    end

  end

  def show
      @aluno = Aluno.find(params[:id])
  end

  private
  def aluno_params
    params.require(:aluno).permit(:nome, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alunos/new.html.erb
<h1>Novo aluno</h1>

<% if @aluno.errors.any? %>
<div id="error_explanation">
    <h2>
    <%= @aluno.errors.count %> erro(s) impedem que o aluno seja salvo:
    </h2>
    <ul>
    <% @aluno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
</div>
<% end %>


<%= form_with scope: :aluno, url: alunos_path, local: true do |form| %>
  <p>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.submit 'Salvar novo aluno' %>
  </p>
<% end %>

app/views/alunos/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TESTE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>